config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  get 'home/show'
  get '/product/get_box_code/' => 'products#get_box_code'
  get '/stock/get_batch_no/' => 'stocks#get_batch_no'
  get '/stock/get_sales_price/' => 'stocks#get_sales_price'

  devise_for :models
  resources :sales_order_details

  get '/close/:id' => 'sales_order_details#close', as: 'closes'

  resources :sales_orders

  resources :stocks

  resources :product_types

  resources :products

  resources :companies

  resources :customers

end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
  def get_product_type_name(product_type_id)
    return ProductType.find(product_type_id)
  end
end

app/views/product_types/_form.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><%= params[:action].camelize %> Product</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@product_type) do |f| %>
            <% if @product_type.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

                  <ul>
                    <% @product_type.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="field">
              <%= f.label :product_name %>
              <%= f.text_field :name %>
            </div>
            <br/>
            <div class="actions">
              <%= f.submit :class=>"btn btn-info"%>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/product_types/edit.html.erb
<%= render 'form' %>

app/views/product_types/index.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Product Types</h3>
      </div>
      <div class="panel-body">
        <div class="text-right"><%= link_to 'New Product Type', new_product_type_path,:class=>"btn btn-info" %></div>
        <br/>
        <table class="table table-responsive">
          <thead>
          <tr>
            <th>Name</th>
            <th colspan="2"></th>
          </tr>
          </thead>

          <tbody>
          <% @product_types.each do |product_type| %>
              <tr>
                <td width="71%"><%= product_type.name %></td>
                <td width="10%"><%= link_to 'Show', product_type %></td>
                <td width="9%"><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/product_types/new.html.erb
<%= render 'form' %>

app/views/product_types/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Product Type Detail</h3>
      </div>
      <div class="panel-body">
        <div class="text-right"><%= link_to 'Edit', edit_product_type_path(@product_type),:class=>"btn btn-info"   %> |
          <%= link_to 'Back', product_types_path,:class=>"btn btn-info"   %></div>
        <br/>
        <p id="notice"><%= notice %></p>
        <table class="table table-responsive">
        <tr>
          <td width="30%">Product Type Name : </td>
          <td width="70%"><%= @product_type.name %></td>
        </tr>
        </table>
      </div>
    </div>
  </div>
</div>