config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  get 'home/show'
  get '/product/get_box_code/' => 'products#get_box_code'
  get '/stock/get_batch_no/' => 'stocks#get_batch_no'
  get '/stock/get_sales_price/' => 'stocks#get_sales_price'

  devise_for :models
  resources :sales_order_details

  get '/close/:id' => 'sales_order_details#close', as: 'closes'

  resources :sales_orders

  resources :stocks

  resources :product_types

  resources :products

  resources :companies

  resources :customers

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales_orders
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
end

app/models/sales_order.rb
class SalesOrder < ActiveRecord::Base
  belongs_to :customer
  has_many :sales_order_details
end

app/models/sales_order_detail.rb
class SalesOrderDetail < ActiveRecord::Base
  belongs_to :stock
  belongs_to :sales_order
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  belongs_to :product_type
  belongs_to :company
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def get_box_code
    @box_code=Product.where(:company_id=>params[:company_id],:product_type_id=>params[:product_type_id])
    respond_to do |format|
      format.json { render json: @box_code }
    end
  end
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:company_id, :product_type_id, :box_code)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json


  def get_batch_no
    @batch_no=Stock.where(:company_id=>params[:company_id],:product_type_id=>params[:product_type_id],:product_id=>params[:product_id]).where.not(:quantity=>0)
    respond_to do |format|
      format.json { render json: @batch_no }
    end
  end
  def get_sales_price
    @sales_price=Stock.find(params[:stock_id])
    respond_to do |format|
      format.json { render json: @sales_price }
    end
  end


  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:company_id, :product_type_id, :product_id, :batch_no, :quantity, :purchase_price, :sales_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
  def get_product_type_name(product_type_id)
    return ProductType.find(product_type_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_orders_helper.rb
module SalesOrdersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= (name == 'alert') ? "error" : "success" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
    <div class="navbar-header"> <%= link_to "Gopinath Enterprise", root_path, :class => 'brand' %></div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if model_signed_in? %>
              <li class="<%= 'active' if params[:controller]=='home'%>"><%= link_to 'Home', root_path %></li>
              <li class="<%= 'active' if params[:controller]=='customers'%>"><%= link_to 'Customer', customers_path %></li>
              <li class="<%= 'active' if params[:controller]=='companies'%>"><%= link_to 'Company', companies_path %></li>
              <li class="<%= 'active' if params[:controller]=='products'%>"><%= link_to 'Product', products_path %></li>
              <li class="<%= 'active' if params[:controller]=='stocks'%>"><%= link_to 'Stock', stocks_path %></li>
              <li class="<%= 'active' if params[:controller]=='sales_orders' || params[:controller]=='sales_order_details'%>"><%= link_to 'Sales Order', sales_orders_path %></li>
              <li class="<%= 'active' if params[:controller]=='product_types'%>"><%= link_to 'Product Type', product_types_path %></li>
              <li class="<%= 'active' if params[:controller]=='devise/registrations'%>">
                <%= link_to 'Change Password', edit_model_registration_path %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_model_session_path, :method=>'delete' %>
              </li>
          <% else %>
              <li class="<%= 'active' if params[:controller]=='devise/sessions'%>">
                <%= link_to 'Login', new_model_session_path %>
              </li>
              <li class="<%= 'active' if params[:controller]=='devise/registrations'%>">
                <%= link_to 'Sign up', new_model_registration_path %>
              </li>
              <li class="<%= 'active' if params[:controller]=='devise/passwords'%>">
                <%= link_to 'Forgot Password?', new_model_password_path %>
              </li>
          <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>Gopinath Enterprise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    input{
        height: 35px !important;
    }
  </style>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<div class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</div>
<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>

</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>